-- Payment-term descriptions from the company's SAP list (2026-09-27; backlog 24). SAP's supplier data carries only
-- the codes. Updates the codes that are already in scm.PaymentTerm (the supplier sync adds codes, never descriptions,
-- so it does not overwrite these); a code added later is described in Configuration → Shipping terms. Codes without a
-- description in the list (ME20, ME90, PAYT) keep what they have.
UPDATE p SET Description = v.Description
FROM scm.PaymentTerm p
JOIN (VALUES
    (N'ME07', N'Month End + 07 Days'),
    (N'ME10', N'Month End + 10 Days'),
    (N'ME15', N'Month End + 15 Days'),
    (N'ME30', N'Month End + 30 Days'),
    (N'ME40', N'Month End + 40 Days'),
    (N'ME45', N'Month End + 45 Days'),
    (N'ME60', N'Month End + 60 Days'),
    (N'N000', N'Net 0 Days'),
    (N'N001', N'Net 1 Day'),
    (N'N002', N'Net 2 Days'),
    (N'N003', N'Net 3 Days'),
    (N'N004', N'Net 4 Days'),
    (N'N005', N'Net 5 Days'),
    (N'N006', N'Net 6 Days'),
    (N'N007', N'Net 7 Days'),
    (N'N010', N'Net 10 Days'),
    (N'N014', N'Net 14 Days'),
    (N'N015', N'Net 15 Days'),
    (N'N020', N'Net 20 Days'),
    (N'N021', N'Net 21 Days'),
    (N'N030', N'Net 30 Days'),
    (N'N035', N'Net 35 Days'),
    (N'N040', N'Net 40 Days'),
    (N'N045', N'Net 45 Days'),
    (N'N060', N'Net 60 Days'),
    (N'N075', N'Net 75 Days'),
    (N'N090', N'Net 90 Days'),
    (N'S001', N'10% in Advance, Balance upon Delivery'),
    (N'S002', N'100% before Delivery'),
    (N'S004', N'100% upon Delivery'),
    (N'S005', N'100% in advance'),
    (N'S006', N'15% in Advance, Balance before Delivery'),
    (N'S007', N'15% in Advance, Balance Upon Delivery'),
    (N'S008', N'20% in Advance, Balance before Delivery'),
    (N'S009', N'20% in Advance, Balance Upon Delivery'),
    (N'S010', N'25% in Advance, Balance before Delivery'),
    (N'S011', N'25% in Advance, Balance Upon Delivery'),
    (N'S012', N'30% in Advance, Balance before Delivery'),
    (N'S013', N'30% in Advance, Balance Upon Delivery'),
    (N'S014', N'35% in Advance, Balance before Delivery'),
    (N'S015', N'35% in Advance, Balance Upon Delivery'),
    (N'S016', N'40% in Advance, Balance before Delivery'),
    (N'S017', N'40% in Advance, Balance Upon Delivery'),
    (N'S018', N'45% in Advance, Balance before Delivery'),
    (N'S019', N'45% in Advance, Balance Upon Delivery'),
    (N'S020', N'5% in Advance, Balance before Delivery'),
    (N'S021', N'5% in Advance, Balance Upon Delivery'),
    (N'S022', N'50% in Advance, Balance before Delivery'),
    (N'S023', N'50% in Advance, Balance Upon Delivery'),
    (N'S024', N'55% in Advance, Balance before Delivery'),
    (N'S025', N'55% in Advance, Balance upon Delivery'),
    (N'S026', N'60% in Advance, Balance before Delivery'),
    (N'S027', N'60% in Advance, Balance Upon Delivery'),
    (N'S028', N'65% in Advance, Balance before Delivery'),
    (N'S029', N'65% in Advance, Balance Upon Delivery'),
    (N'S030', N'70% in Advance, Balance before Delivery'),
    (N'S031', N'70% in Advance, Balance Upon Delivery'),
    (N'S032', N'75% in Advance, Balance before Delivery'),
    (N'S033', N'75% in Advance, Balance Upon Delivery'),
    (N'S034', N'80% in Advance, Balance before Delivery'),
    (N'S035', N'80% in Advance, Balance Upon Delivery'),
    (N'S036', N'85% in Advance, Balance before Delivery'),
    (N'S037', N'85% in Advance, Balance Upon Delivery'),
    (N'S038', N'90% in Advance, Balance before Delivery'),
    (N'S039', N'90% in Advance, Balance Upon Delivery'),
    (N'S040', N'95% in Advance, Balance before Delivery'),
    (N'S041', N'95% in Advance, Balance Upon Delivery'),
    (N'S042', N'Customer Deposit'),
    (N'S043', N'Customer Deposit - AH'),
    (N'S044', N'Customer Deposit - BU'),
    (N'S045', N'Customer Deposit - DM'),
    (N'S046', N'Customer Deposit - JD'),
    (N'S047', N'Customer Deposit - KH'),
    (N'S048', N'Customer Deposit - MD'),
    (N'S049', N'Customer Deposit -MK'),
    (N'S050', N'Customer Deposit - RD'),
    (N'S051', N'Customer Deposit - TB'),
    (N'S052', N'Cash Sales Payment Al Hasa'),
    (N'S053', N'Cash Sales Payment Buraidah'),
    (N'S054', N'Cash Sales Payment Dammam'),
    (N'S055', N'Cash Sales Payment Jeddah'),
    (N'S056', N'Cash Sales Payment Khamis'),
    (N'S057', N'Cash Sales Payment Madinah'),
    (N'S058', N'Cash Sales Payment Makkah'),
    (N'S059', N'Cash Sales Payment Riyadh'),
    (N'S060', N'Cash Sales Payment Tabuk')
) AS v (Code, Description) ON v.Code = p.Code;
